[exception_details_await_promise.py]
  [test_exception_details_await_promise[[1, 2\][Symbol.iterator\]()-expected28\]]
    bug: 1853953

  [test_exception_details_await_promise['mystring'[Symbol.iterator\]()-expected29\]]
    bug: 1853953

  [test_exception_details_await_promise[(new Set([1,2\]))[Symbol.iterator\]()-expected30\]]
    bug: 1853953

  [test_exception_details_await_promise[(new Map([[1,2\]\]))[Symbol.iterator\]()-expected31\]]
    bug: 1853953
